# 文字雲
## 2018/07/11
## 利用爬蟲抓取PTT科技業板(Tech_Job)的文章，並繪出文字雲。

###載入Package
```{r}
library(xml2)
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
source('pttTestFunction.R')
```


###網路爬蟲，抓取文章存為TXT檔
```{r}
id = c(3125:3135)
URL = paste0("https://www.ptt.cc/bbs/Tech_Job/index", id, ".html")
filename = paste0(id, ".txt")
#mapply(pttTestFunction, 
#       URL = URL, filename = filename)
```

###文本清理，過濾無意義的文字
```{r, error=FALSE, warning=FALSE, message=FALSE}
rm(list=ls(all.names = TRUE))

filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
})

docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "文章網址")
docs <- tm_map(docs, toSpace, "引述")
docs <- tm_map(docs, toSpace, "之銘言")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "來自")
docs <- tm_map(docs, toSpace, "時間")
docs <- tm_map(docs, toSpace, "推文")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "已")
docs <- tm_map(docs, toSpace, "為")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "阿")
docs <- tm_map(docs, toSpace, "做")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "個")

#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)

docs
```

###列出詞頻矩陣
```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

###繪製文字雲
```{r}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=70,max.words=100,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```